---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: check-merge-conflict
          - id: check-json
          - id: check-yaml
          - id: check-xml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: pretty-format-json
            args: [--indent=4]

          - id: requirements-txt-fixer
          - id: trailing-whitespace

    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.4
      hooks:
          - id: autopep8

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11
      hooks:
          - id: yamlfmt


    - repo: https://github.com/IamTheFij/docker-pre-commit
      rev: v2.0.0
      hooks:
          - id: docker-compose-check
