---
version: '3'
services:
    postgres:
        image: postgres:10.3
        container_name: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - 5432:5432
    webserver:
        build:
            dockerfile: ./Dockerfile
            context: ./
        env_file:
            - .env
        restart: always
        depends_on:
            - postgres
        ports:
            - 8080:8080
        entrypoint: /usr/local/airflow/run_webserver.sh
        healthcheck:
            test: [CMD-SHELL, '[ -f /usr/local/airflow/airflow-webserver.pid ]']
            interval: 30s
            timeout: 30s
            retries: 3
    scheduler:
        build:
            dockerfile: ./Dockerfile
            context: ./
        env_file:
            - .env
        restart: always
        depends_on:
            - webserver
        entrypoint: /usr/local/airflow/run_scheduler.sh
    # entrypoint: airflow scheduler
        healthcheck:
            test: [CMD-SHELL, '[ -f /usr/local/airflow/airflow-scheduler.pid ]']
            interval: 30s
            timeout: 30s
            retries: 3
